AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function triggered by SQS and writing to DynamoDB
Parameters:
  ServerlessWebBackendProjectBucket:
    Type: String
    Description: S3 bucket where the CloudFormation templates associated with this project are stored
    Default: "serverless-web-backend-project-bucket"
  ProjectName:
    Type: String
    Description: Name of the project (used for resource naming)
    Default: "ServerlessWebBackend"
  S3Bucket:
    Type: String
    Description: S3 bucket where the Lambda function code is stored
  S3Key:
    Type: String
    Description: S3 key for the Lambda function code zip file

Resources:
  LambdaFunctionApiGwToDynamoDB:  
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_sqs_dynamodb.put_item
      # The machine architecture to run code on.
      Architectures: 
        - arm64
      Runtime: python3.12
      # CapacityProviderConfig:
      #   CapacityProviderConfig
      Code: 
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Role: !GetAtt RoleLambdaSQSDanamoDB.Arn
      # CodeSigningConfigArn: String
      # DeadLetterConfig: 
      #   DeadLetterConfig
      # Description: String
      # DurableConfig: 
      #   DurableConfig
      # Environment: 
      #   Environment
      # EphemeralStorage: 
      #   EphemeralStorage
      # FileSystemConfigs: 
      #   - FileSystemConfig
      # FunctionName: String
      # FunctionScalingConfig: 
      #   FunctionScalingConfig
      # ImageConfig: 
      #   ImageConfig
      # KmsKeyArn: String
      # Layers: 
      #   - String
      # LoggingConfig: 
      #   LoggingConfig
      # MemorySize: Integer
      # PackageType: String
      # PublishToLatestPublished: Boolean
      # RecursiveLoop: String
      # ReservedConcurrentExecutions: Integer
      # Runtime: String
      # RuntimeManagementConfig: 
      #   RuntimeManagementConfig
      # SnapStart: 
      #   SnapStart
      # Tags: 
      #   - Tag
      # TenancyConfig: 
      #   TenancyConfig
      # Timeout: Integer
      # TracingConfig: 
      #   TracingConfig
      # VpcConfig: 
      #   VpcConfig
  RoleLambdaSQSDanamoDB:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
             # TODO: Make the service specific to your account and region, e.g. lambda.amazonaws.com
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaHandleSQSQueuePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                - 'sqs:ReceiveMessage'
                - 'sqs:DeleteMessage'
                - 'sqs:GetQueueAttributes'
                - 'sqs:ChangeMessageVisibility'
                Resource: !ImportValue QueueArn-SQS-APIGW-Lambda
        - PolicyName: LambdaWriteToDynamoDBPolicy
          PolicyDocument: 
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:DescribeTable'
                Resource: !ImportValue TableArn-DynamoDB-Lambda
  # EventSourceMapping: Consumer configuration
  SQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !ImportValue QueueArn-SQS-APIGW-Lambda
      FunctionName: !Ref LambdaFunctionApiGwToDynamoDB
      BatchSize: 10
      Enabled: true
  # RootInstanceProfile:
  #   Type: 'AWS::IAM::InstanceProfile'
  #   Properties:
  #     Path: /
  #     Roles:
  #       - !Ref RoleLambdaSQSDanamoDB

Outputs:
  LambdaFunctionApiGwToDynamoDBArn:
    Description: ARN of the Lambda function that will be triggered by API Gateway
    Value: !GetAtt LambdaFunctionAPIGWToDynamoDB.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionApiGwToDynamoDBArn"
