AWSTemplateFormatVersion: '2010-09-09'
Description: SQS queue service with API Gateway to trigger Lambda function
# ---------------------------------------------------------------
# Sections
#   Parameters
#   Resources
#     - SQSQueueApiGwToLambdaFunction
#   Outputs
# ---------------------------------------------------------------
  
Parameters:
  ProjectName:
    Type: String
    Description: Name of the project (used for resource naming)
    Default: "ServerlessWebBackend"

Resources:
  SQSQueueApiGwToLambdaFunction:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${ProjectName}-api-gw-to-lambda-function-queue"
      # ContentBasedDeduplication: Boolean
      # DelaySeconds: Integer
      # FifoQueue: false
      # KmsDataKeyReusePeriodSeconds: Integer
      # KmsMasterKeyId: String
      MaximumMessageSize: 2048  # 2KB in bytes
      MessageRetentionPeriod: 86400  # 1 days in seconds
      # QueueArn: String
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 180   # 6× a 30s Lambda timeout
      # RedrivePolicy: 
      #   RedrivePolicy
      # Tags: 
      #   - Tag
Outputs:
  QueueUrl:
    Description: URL of the SQS queue
    Value: !Ref SQSQueueApiGwToLambdaFunction
    Export:
      Name: !Sub "${AWS::StackName}-api-gw-to-lambda-function-queue-url"
  QueueArn:
    Description: ARN of the SQS queue
    Value: !GetAtt SQSQueueApiGwToLambdaFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-api-gw-to-lambda-function-queue-arn"
  QueueName:
    Description: Name of the SQS queue
    Value: !GetAtt SQSQueueApiGwToLambdaFunction.QueueName
    Export:
      Name: !Sub "${AWS::StackName}-api-gw-to-lambda-function-queue-name"
